name: Build and release zip file
on:
  push:
    tags:
      - '*'

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.5.0

    - name: Install zip
      run: sudo apt update && sudo apt install zip -y

    - name: Zip the plugin
      run: zip -r plugin.video.polpetta-stream-${{github.ref_name}}.zip ./*

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: plugin.video.polpetta-stream-${{github.ref_name}}.zip
        draft: true
        prerelease: true